# Generated by Django 3.2.9 on 2022-01-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_a_glance', models.TextField(max_length=250)),
                ('message_from_ceo', models.TextField(max_length=250)),
                ('company_profile', models.TextField(max_length=250)),
                ('our_concern', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Enter Your Name')),
                ('phone', models.CharField(max_length=255, verbose_name='Enter Your Phone Number')),
                ('date', models.DateField(verbose_name='Enter Pickup Date')),
                ('type_of_ambulance', models.IntegerField(choices=[(1, 'AC'), (2, 'NON AC'), (2, 'FREEZING')], verbose_name='Enter Ambulance Type')),
                ('pickup_location', models.CharField(max_length=255, verbose_name='Enter Pickup Location')),
                ('destination', models.CharField(max_length=255, verbose_name='Enter Destination')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
