# Generated by Django 3.2.9 on 2022-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='at_a_glance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='company_profile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='message_from_ceo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_concern',
            field=models.TextField(),
        ),
    ]
