# Generated by Django 3.2.9 on 2022-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0002_auto_20220118_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Put a Title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('blog_content', models.TextField(verbose_name='Blog Content Write Here')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Image')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
