# Generated by Django 3.2.9 on 2022-01-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0004_remove_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=255, verbose_name='Put Services Title')),
                ('services_details', models.TextField(verbose_name='Services Content Write Here')),
                ('services_image', models.ImageField(blank=True, null=True, upload_to='services_images', verbose_name='Image')),
            ],
        ),
    ]
