# Generated by Django 3.2.9 on 2022-01-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0006_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_background_image', models.ImageField(blank=True, null=True, upload_to='background_image', verbose_name='first_background_image')),
                ('second_background_image', models.ImageField(blank=True, null=True, upload_to='background_image', verbose_name='second_background_image')),
                ('third_background_image', models.ImageField(blank=True, null=True, upload_to='background_image', verbose_name='third_background_image')),
            ],
        ),
    ]
