# Generated by Django 3.2.9 on 2022-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0007_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='first_background_details',
            field=models.TextField(default='', verbose_name='Background Details Write Here'),
        ),
        migrations.AddField(
            model_name='background',
            name='first_background_title',
            field=models.CharField(default='', max_length=255, verbose_name='Enter Background Title'),
        ),
        migrations.AddField(
            model_name='background',
            name='second_background_details',
            field=models.TextField(default='', verbose_name='Background Details Write Here'),
        ),
        migrations.AddField(
            model_name='background',
            name='second_background_title',
            field=models.CharField(default='', max_length=255, verbose_name='Enter Background Title'),
        ),
        migrations.AddField(
            model_name='background',
            name='third_background_details',
            field=models.TextField(default='', verbose_name='Background Details Write Here'),
        ),
        migrations.AddField(
            model_name='background',
            name='third_background_title',
            field=models.CharField(default='', max_length=255, verbose_name='Enter Background Title'),
        ),
    ]
