# Generated by Django 3.2.9 on 2022-01-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0009_auto_20220119_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type_of_ambulance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.services'),
        ),
    ]
